// my-react-playlist-app/src/components/Sidebar.jsx
import React from 'react';

function Sidebar({
  isOpen,
  onClose,
  userInfo,
  onLogin,
  onLogout,
  pinnedPlaylists,
  onSelectPinned,
  currentTheme,
  onToggleTheme
}) {
  return (
    <>
      <div
        className={`fixed inset-0 bg-black opacity-50 z-40 md:hidden ${isOpen ? '' : 'hidden'}`}
        onClick={onClose}
      ></div>

      <div className={`fixed z-50 top-0 left-0 h-full w-64 bg-[var(--bg-secondary)] transform transition-transform duration-300 ease-in-out md:static md:translate-x-0 ${isOpen ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="flex flex-col h-full p-4">
          <div className="flex items-center justify-between pb-4 border-b border-[var(--border-color)]">
            <div className="flex items-center space-x-2">
              <i className="fas fa-robot text-green-400"></i>
              <h2 className="text-[var(--text-primary)] text-lg font-semibold">AI Playlist</h2>
            </div>
            <button onClick={onClose} className="md:hidden text-gray-400 hover:text-white transition-colors">
              <i className="fas fa-times"></i>
            </button>
          </div>
          <div className="mt-4 flex flex-col items-center">
            <img src={userInfo.avatar} alt="User Avatar" className="w-16 h-16 rounded-full mb-2" />
            <span className="text-lg font-medium text-[var(--text-primary)] break-words w-full text-center">{userInfo.displayName}</span>
            {!userInfo.isLoggedIn ? (
              <button onClick={onLogin} className="mt-4 w-full py-2 px-4 rounded-full font-medium transition-colors bg-green-500 text-white hover:bg-green-600">
                <i className="fab fa-spotify mr-2"></i> เข้าสู่ระบบด้วย Spotify
              </button>
            ) : (
              <button onClick={onLogout} className="mt-2 w-full py-2 px-4 rounded-full font-medium transition-colors bg-red-500 text-white hover:bg-red-600">
                <i className="fas fa-sign-out-alt mr-2"></i> ออกจากระบบ Spotify
              </button>
            )}
          </div>
          <div className="flex-grow p-2 overflow-y-auto mt-4 border-t border-[var(--border-color)]">
            <h3 className="text-sm font-semibold text-gray-400 mb-2 px-2 pt-2">ประวัติเพลย์ลิสต์ที่ Pin ไว้</h3>
            <div className="space-y-1">
              {pinnedPlaylists.map((item, index) => (
                <button key={index} onClick={() => onSelectPinned(index)} className="w-full text-left text-sm p-2 rounded-lg hover:bg-gray-700 transition-colors text-gray-300">
                  <div className="font-medium">{item.name}</div>
                  <div className="text-xs text-gray-400">Pinned on: {new Date(item.timestamp).toLocaleDateString('th-TH')}</div>
                </button>
              ))}
            </div>
          </div>
          <div className="mt-auto pt-4 border-t border-[var(--border-color)]">
            <button
              onClick={onToggleTheme}
              className="w-full flex items-center justify-between py-2 px-4 rounded-lg text-gray-300 hover:bg-opacity-50 hover:bg-gray-500 transition-colors"
            >
              <span>
                {currentTheme === 'dark' ? <><i className="fas fa-sun mr-2"></i> โหมดกลางวัน</> : <><i className="fas fa-moon mr-2"></i> โหมดกลางคืน</>}
              </span>
            </button>
          </div>
        </div>
      </div>
    </>
  );
}

export default Sidebar;

// UI/src/lib/components/Sidebar.svelte
<script lang="ts">
    import { onMount } from 'svelte';

    //--- ตัวแปรสำหรับเก็บข้อมูลผู้ใช้ ---
    let isLoggedIn = false;
    let displayName = 'User';
    let avatarUrl = 'https://placehold.co/100x100/1DB954/ffffff?text=U';

    //--- ตัวแปรสำหรับสลับธีม ---
    let currentTheme = 'dark';
    let themeIconClass = 'fas fa-sun';
    let themeText = 'โหมดกลางวัน';

    // onMount คือฟังก์ชันที่จะรันแค่ครั้งเดียวหลังจากที่ Component ถูกสร้างเสร็จ
    // เหมาะสำหรับการดึงข้อมูลเริ่มต้น เช่น เช็คว่าผู้ใช้ล็อกอินอยู่หรือไม่
    onMount(() => {
        // ลองดึงข้อมูลจาก localStorage
        const storedToken = localStorage.getItem('spotify_access_token');
        const storedName = localStorage.getItem('spotify_display_name');
        const storedAvatar = localStorage.getItem('spotify_avatar');
        
        if (storedToken && storedName) {
            isLoggedIn = true;
            displayName = storedName;
            avatarUrl = storedAvatar || avatarUrl;
        }

        // ตั้งค่าธีมเริ่มต้น
        const storedTheme = localStorage.getItem('theme') || 'dark';
        applyTheme(storedTheme);
    });

    function handleLogin() {
        // **สำคัญ:** แก้ URL ให้ชี้ไปที่ FastAPI ของคุณ
        window.location.href = 'http://127.0.0.1:8000/spotify_login';
    }

    function handleLogout() {
        localStorage.clear();
        // รีโหลดหน้าเพื่อให้ UI อัปเดต
        window.location.reload();
    }
    
    function applyTheme(theme: string) {
        currentTheme = theme;
        if (theme === 'light') {
            document.documentElement.classList.remove('dark');
            themeIconClass = 'fas fa-moon';
            themeText = 'โหมดกลางคืน';
        } else {
            document.documentElement.classList.add('dark');
            themeIconClass = 'fas fa-sun';
            themeText = 'โหมดกลางวัน';
        }
        localStorage.setItem('theme', theme);
    }

    function toggleTheme() {
        applyTheme(currentTheme === 'dark' ? 'light' : 'dark');
    }

</script>

<div class="fixed z-50 top-0 left-0 h-full w-64 bg-gray-100 dark:bg-gray-800 md:static transform transition-transform duration-300 ease-in-out">
    <div class="flex flex-col h-full p-4">
        <div class="flex items-center justify-between pb-4 border-b border-gray-300 dark:border-gray-700">
            <div class="flex items-center space-x-2">
                <i class="fas fa-robot text-green-400"></i>
                <h2 class="text-gray-900 dark:text-white text-lg font-semibold">AI Playlist</h2>
            </div>
        </div>

        <div class="mt-4 flex flex-col items-center">
            <img src={avatarUrl} alt="User Avatar" class="w-16 h-16 rounded-full mb-2">
            <span class="text-lg font-medium text-gray-900 dark:text-white break-words w-full text-center">{displayName}</span>

            {#if isLoggedIn}
                <button on:click={handleLogout} class="mt-2 w-full py-2 px-4 rounded-full font-medium transition-colors bg-red-500 text-white hover:bg-red-600">
                    <i class="fas fa-sign-out-alt mr-2"></i> ออกจากระบบ Spotify
                </button>
            {:else}
                <button on:click={handleLogin} class="mt-4 w-full py-2 px-4 rounded-full font-medium transition-colors bg-green-500 text-white hover:bg-green-600">
                    <i class="fab fa-spotify mr-2"></i> เข้าสู่ระบบด้วย Spotify
                </button>
            {/if}
        </div>

        <div class="flex-grow"></div>

        <div class="mt-4 pt-4 border-t border-gray-300 dark:border-gray-700">
            <button on:click={toggleTheme} class="w-full flex items-center justify-between py-2 px-4 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors">
                <span><i class="{themeIconClass} mr-2"></i> {themeText}</span>
            </button>
        </div>
    </div>
</div>
